### Shows the health of the application
GET {{basepath}}/actuator/health

### Creates a new ics file given a correct TimeEdit Url
< {%
    request.variables.set("url", "https://cloud.timeedit.net/hvl/web/studbergen/ri6305Q64k59u6QZQtQn270QZQ8QY43dZ6317Z0y6580CwtZ00AZ87D9690F55D7EAEBF27863FFDA6.ics")
%}
PUT {{basepath}}/create
Content-Type: text/plain

{{url}}

### Gets the ics file for a given TimeEdit Url
< {%
    request.variables.set("path", "ri6305Q64k59u6QZQtQn270QZQ8QY43dZ6317Z0y6580CwtZ00AZ87D9690F55D7EAEBF27863FFDA6.ics")
%}
GET {{basepath}}/get/{{path}}